[versions]
agp = "8.10.1"
androidxRecyclerview = "1.3.2"
converterGson = "2.9.0"
firebaseBom = "33.13.0"
firebaseDatabase = "21.0.0"
fragment = "1.6.2"
generativeaiVersion = "0.3.0"
googleGoogleMapsServices = "2.2.0"
googleMapsServices = "0.15.0"
googlePlayServicesLocation = "18.0.0"
googlePlayServicesLocationVersion = "21.0.1"
googlePlayServicesMaps = "17.0.0"
imagepicker = "2.1"
json = "20230227"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseAuth = "23.2.0"
firebaseFirestore = "25.1.4"
gridlayout = "1.1.0"
mpandroidchart = "v3.1.0"
mpandroidchartVersion = "v3.1.0"
okhttp = "4.10.0"
okhttpVersion = "4.12.0"
picasso = "2.71828"
playServicesLocation = "21.3.0"
playServicesLocationVersion = "17.0.0"
playServicesMaps = "19.2.0"
playServicesMapsVersion = "18.2.0"
recyclerview = "1.4.0"
recyclerviewVersion = "1.2.1'  // Assure-toi d'avoir la derni√®re version"
firebaseStorage = "21.0.2"
retrofitVersion = "2.9.0"
slf4jSimple = "1.7.25"

[libraries]
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
google-firebase-storage = { module = "com.google.firebase:firebase-storage" }
google-generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeaiVersion" }
google-maps-services = { module = "com.google.maps:google-maps-services", version.ref = "googleMapsServices" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
maps-google-maps-services-v220 = { module = "com.google.maps:google-maps-services", version.ref = "googleGoogleMapsServices" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
mpandroidchart = { module = "om.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-v4120 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
philjay-mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchartVersion" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-location-v1700 = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
play-services-location-v1800 = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayServicesLocation" }
play-services-location-v2101 = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayServicesLocationVersion" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services-maps-v1700 = { module = "com.google.android.gms:play-services-maps", version.ref = "googlePlayServicesMaps" }
play-services-maps-v1820 = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
recyclerview-v121assuretoidavoirladernireversion = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
recyclerview-v132 = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

